[project]
name = "A2rchi"
version = "0.1.0"
description = "An AI Augmented Research Chat Intelligence (A2rchi)"
requires-python = ">=3.7"
# sorted alphabetically by last name
authors = [
    {name="Julius Heitkoetter", email="juliush@mit.edu"},
    {name="Time Kraska", email="kraska@mit.edu"},
    {name="Ludovico Mori", email="mori25@mit.edu"},
    {name="Christoph Paus", email="paus@mit.edu"},
    {name="Matthew Russo", email="mdrusso@mit.edu"},
]
dependencies = [
    "accelerate==0.23.0",
    "backoff==2.2.1",
    "beautifulsoup4==4.12.2",
    "bitsandbytes==0.41.1",
    "chromadb==0.4.8",
    "clickhouse-connect==0.6.6",
    "coloredlogs==15.0.1",
    "duckdb==0.8.1",
    "fastapi==0.99.1",
    "flask==2.3.3",
    "flask-cors==4.0.0",
    "flatbuffers==23.5.26",
    "hnswlib==0.7.0",
    "httptools==0.6.0",
    "humanfriendly==10.0",
    "langchain==0.0.268",
    "lz4==4.3.2",
    "monotonic==1.6",
    "onnxruntime==1.15.1",
    "openai==0.27.9",
    "overrides==7.3.1",
    "pandas==2.1.0",
    "peft==0.5.0",
    "posthog==3.0.1",
    "pulsar-client==3.2.0",
    "python-dotenv==1.0.0",
    "python-redmine==2.4.0",
    "regex==2023.6.3",
    "requests==2.31.0",
    "scipy==1.11.2",
    "sentencepiece==0.1.99",
    "sympy==1.12",
    "tiktoken==0.4.0",
    "tokenizers==0.13.3",
    "torch==2.0.1",
    "transformers==4.33.1",
    "uvloop==0.17.0",
    "watchfiles==0.19.0",
    "zstandard==0.21.0",
]

[tool.setuptools]
packages = [
    "A2rchi",
    "A2rchi.bin",
    "A2rchi.chains",
    "A2rchi.interfaces",
    "A2rchi.interfaces.chat_app",
    "A2rchi.interfaces.uploader_app",
    "A2rchi.utils",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backed = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/mit-submit/A2rchi"
